### ISSUE TITLE
✨ Create utility classes and attributes for each CSS variable. 

### ISSUE THREAD

**Issue by hayleigh-dot-dev** [lustre-labs/lustre_ui#3]
Lustre_ui defines a bunch of CSS variables that should make it easier to write good-looking components. 

Utility CSS frameworks (Tailwind et al) can also be a joy to use for one-off or low-commitment designs. It'd be great if each of these CSS variables were exposed to uses through a bunch of utility classes they could use however they like.

For example:
```css
.bg-element {
  background-color: var(--element-background);
}

.text-xl {
  font-size: var(--text-2xl);
}
```
```gleam
// lustre/ui/utils

pub fn bg_element() -> Attribute(msg) {
  attribute.class("bg-element")
}

pub fn text_xl() -> Attribute(msg) {
  attribute.class("text-xl")
}
```
